apiVersion: v1
kind: Service
metadata:
  name: ${serviceName}
  labels:
    app: ${serviceName}
spec:
  ports:
    - port: ${server.port}
      protocol: TCP
      targetPort: ${server.port}
  selector:
    app: ${serviceName}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${serviceName}
spec:
  selector:
    matchLabels:
      app: ${serviceName}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${serviceName}
    spec:
      containers:
        - name: ${serviceName}
          image: ${imageName}:${version}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ${configMapTemplateName}
          ports:
            - containerPort: ${server.port}

